#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

source scripts/environment

scripts/test_setup

nose2 --plugin nose2.plugins.junitxml --junit-xml --with-coverage --start-dir tests/unit_tests/
