#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

source scripts/environment

scripts/test_setup

pylint --generate-rcfile > pylint.cfg
sed -i 's/output-format=text/output-format=parseable/g' pylint.cfg
pylint --rcfile=pylint.cfg $(find {app.py,database,masters} -type f -name '*.py' -print) > pylint.log || exit 0
